#' Draw Modules
#'
#'
#' @param graph an \code{\link[igraph]{igraph}} object, which can be generated by
#' \code{\link{generate.network}}.
#' @param title a name for the Cytoscape session.
#' @param nodes a \code{\link[data.table]{data.table}} with data containing the nodes.
#' It is contained in the output list of \code{\link{identify.modules}}.
#' @param modules a \code{\link[data.table]{data.table}} with data containing the nodes in the modules.
#' It is contained in the output list of \code{\link{identify.modules}}.
#' @param close.cycnets.afterwards TRUE, if the windows in the cytoscape environment should be closed
#' after drawing. This might be useful repeated function call.
#' @param save.image TRUE, if modules should be saved as png files.
#' @param modules.to.draw a vector containing the IDs of the modules, that should be drawn.
#' If \code{NULL}, all modules will be drawn.
#'
#' @import RCy3
#' @import data.table
#' @import igraph
#' @importFrom grDevices rainbow
#' @export draw.modules
#' @usage draw.modules(graph, modules.summary, title="", 
#' close.cycnets.afterwards=FALSE, save.image=TRUE, modules.to.draw=NULL)
#' @examples
#' data<-qmdiab.data[, 1:75]
#' annotations<-qmdiab.annos[1:75]
#' net_graph<-generate.network(data=data, annotations=annotations)
#' mods<-identify.modules(graph=net_graph, data=data, annotations = annotations, phenotype = qmdiab.phenos$T2D)
#' \donttest{draw.modules(graph=net_graph, modules.summary=mods, title="modules", save.image=FALSE)}
#'
#' @references
#' \insertRef{Shannon2003}{MoDentify}
#' @references
#' \insertRef{Smoot2011}{MoDentify}
#' @references
#' \insertRef{Bot2011}{MoDentify}
#' @references
#' \insertRef{Shannon2013}{MoDentify}

draw.modules<-function(graph, summary, title="", close.cycnets.afterwards=FALSE,
                       save.image=FALSE, modules.to.draw=NULL, only.overview.network=TRUE){
  
  # message("Cytoscape output could take a few minutes...")
  # 
  # nodes <- summary$nodes
  # modules <- summary$modules
  # 
  # nodes<-nodes[, .(moduleID, nodeID, name, label, order.added, node.pval=seed.score,
  #                      after.adding.pval=exp(-score.after.adding))]
  # nodes[, is.significant:=node.pval < (0.05/vcount(graph))]
  # nodes[is.na(moduleID), moduleID:=0]
  # if(is.null(modules.to.draw)){
  #   modules.to.draw<-modules$moduleID
  # }
  # 
  # colors<-rainbow(length(modules.to.draw))
  # names(colors)<-modules.to.draw
  # cy = CytoscapeConnection ()
  # #supressWarnings because of Skipping names on vector!
  # suppressWarnings(draw.network.with.modules(graph, title, nodes, colors, cy=cy, save.image=save.image))
  # 
  # if (!only.overview.network | save.image){
  #   #supressWarnings because of Skipping names on vector!
  #   l<-suppressWarnings(lapply(modules.to.draw, draw.module, graph=graph, title=title, nodes=nodes[!is.na(moduleID)],
  #             colors=colors, cy=cy, save.image=save.image))
  #   }
  # 
  # 
  # if(close.cycnets.afterwards){
  #   deleteAllWindows(cy)
  # }

}
